### ISSUE TITLE
Forge 1.18.2 Crash with REI Plugin Compatibilities

### ISSUE THREAD

**Issue by EldrinFal** [JDDev0/EnergizedPower#2]
Hello,

My game crashed twice today when I clicked on the recipe viewer in the Charger.  Looks like there is something conflicting with REI.  I'm attaching both logs for your review.

Using Energized Power 1.3.6
REI 8.3.588

[crash-2023-02-12_17.31.39-client.txt](https://github.com/JDDev0/EnergizedPower/files/10718991/crash-2023-02-12_17.31.39-client.txt)
[crash-2023-02-12_17.23.21-client.txt](https://github.com/JDDev0/EnergizedPower/files/10718993/crash-2023-02-12_17.23.21-client.txt)

**Comment by JDDev0** [comment]
I can't reproduce it. Can you please send me a list of all installed mods.

**Comment by JDDev0** [comment]
I can't reproduce it. Can you give me more details.
Does the game crash in other inventories too (e.g. Energizer)?

**Comment by JDDev0** [comment]
it seems to be caused by the REI Plugin Compatibilities mod. I still couldn't reproduce the issue, but I have found a way to disable the compatibility layer for my mod. It might be fixed in version 1.18.2-1.3.8. Please try it out and close issue if fixed.

You can download this version here: [CurseForge](https://www.curseforge.com/minecraft/mc-mods/energized-power/files/4395035)

**Comment by EldrinFal** [comment]
That fixed it. Thank you!
